#  Copyright (c) 2012-2025, BdP and DPSG. This file is part of
#  hitobito_pfadi_de and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito_pfadi_de.


# Settings relevant for the hitobito_pfadi_de wagon
# Overrides settings from the main application
application:
  languages:
    de: Deutsch

currency:
  unit: EUR

  # non UI languages for assigning to person#language
  # additional_languages:
  #   en: Englisch

additional_address:
  enabled: true

phone_number:
  predefined_labels:
    - Privat
    - Mobil
    - Arbeit
    - Erziehungsberechtigte
    - Fax
    - Andere

groups:
  period_invoice_templates:
    enabled: true

# The person with this email has root access to everything
# This person should only be used by the operators of the application,
# not the customers.
# Initially, a password reset token may be mailed from the application
# to this address to set a password.
root_email: hitobito-pfadi-de@puzzle.ch

invoice_runs:
  fixed_fees:
    demo_lv_members:
      account: DE56 0483 5035 4099 6000 0
      cost_center: 3007
      receivers:
        layer: Group::Landesverband
        roles:
          - Group::Landesvorstand::Landesschatzmeister
          - Group::Landesvorstand::LandesschatzmeisterStv
          - Group::Landesvorstand::Landesvorsitz
      items:
        - key: aktiv
          unit_cost: 5
          roles:
            - Group::Mitglieder::OrdentlicheMitgliedschaft
        - key: zweitmitgliedschaft
          unit_cost: 2
          roles:
            - Group::Mitglieder::Zweitmitgliedschaft
        - key: foerdermitgliedschaft
          unit_cost: 0.5
          roles:
            - Group::Mitglieder::Foerdermitgliedschaft
    demo_stamm_members:
      account: DE56 0483 5035 4099 6000 0
      cost_center: 3007
      receivers:
        layer: Group::Stamm
        roles:
          - Group::Stamm::Stammesschatzmeister
          - Group::Stamm::StammesschatzmeisterStv
          - Group::Stamm::Stammesfuehrung
      items:
        - key: aktiv
          unit_cost: 7
          roles:
            - Group::Mitglieder::OrdentlicheMitgliedschaft
        - key: zweitmitgliedschaft
          unit_cost: 3
          roles:
            - Group::Mitglieder::Zweitmitgliedschaft
        - key: foerdermitgliedschaft
          unit_cost: 1
          roles:
            - Group::Mitglieder::Foerdermitgliedschaft

people:
  people_managers:
    enabled: true
    self_service_managed_creation:
      enabled: false
